export const proyectos = [
  {
    id: 1,
    titulo: "Contador",
    descripcion: "Aplicación sencilla para contar, aumenta y disminuye su valor en uno, con boton reset, facil para usar desde un celular",
    url: "../AppContador.JPG",
    url_preview: "https://contadordh.netlify.app",
    url_github: "https://github.com/Danielher",
  },
  {
    id: 2,
    titulo: "App TO-DO List",
    descripcion: "Aplicación de lista de tareas, se puede crear, editar y eliminar cada tarea por aparte",
    url: "../AppTodoList.JPG",
    url_preview: "https://aplicaciondetareas.netlify.app",
    url_github: "https://github.com/Danielher",
  },
  {
    id: 3,
    titulo: "Diseño Web Rock Festival",
    descripcion: "Diseño Web Responsivo de una Web para un Festival de Rock",
    url: "../WebRockFestival.JPG",
    url_preview: "https://rock-dan-festival.netlify.app",
    url_github: "https://github.com/Danielher",
  },
  {
    id: 4,
    titulo: "APP KANBAN",
    descripcion: "Proyecto para agregar tareas en un tablero del metodo KABAN",
    url: "../Kanban.JPG",
    url_preview: "https://google.com",
    url_github: "https://github.com/Danielher/M3U2TrelloAppDanielHernandez",
  },
  {
    id: 5,
    titulo: "Landing_Page",
    descripcion: "Creación de Landing Page con React JS y Tailwind",
    url: "../LandingPage.JPG",
    url_preview: "https://landingpagedh.netlify.app/",
    url_github: "https://github.com/Danielher/My_Landing_Page",
  },
  {
    id: 6,
    titulo: "App de Heroes",
    descripcion: "¿Tu de que Team eres?, Marvel o DC?. Prueba esta app para averiguarlo!.",
    url: "../AppHeroes.JPG",
    url_preview: "https://heroesmydc.netlify.app/",
    url_github: "https://github.com/Danielher",
  },
];
