export const proyectos = [
  {
    id: 1,
    titulo: "Contador",
    descripcion: "aplicación sencilla para contar, aumenta y disminuye su valor en uno, con boton reset, facil para usar desde un celular",
    url: "../src/assets/AppContador.JPG",
    url_preview: "https://contadordh.netlify.app",
    url_github: "https://github.com/Danielher",
  },
  {
    id: 2,
    titulo: "App TO-DO List",
    descripcion: "Aplicacion de lista de tareas, se puede crear, editar y eliminar cada tarea por aparte",
    url: "../src/assets/AppTodoList.JPG",
    url_preview: "https://aplicaciondetareas.netlify.app",
    url_github: "https://github.com/Danielher",
  },
  {
    id: 3,
    titulo: "Diseño Web Rock Festival",
    descripcion: "Diseño Web Responsivo de una Web para un Festival de Rock",
    url: "../src/assets/WebRockFestival.JPG",
    url_preview: "https://rock-dan-festival.netlify.app",
    url_github: "https://github.com/Danielher",
  },
  {
    id: 4,
    titulo: "APP KANBAN",
    descripcion: "Proyecto para agregar tareas en un tablero del metodo KABAN",
    url: "../src/assets/Kanban.JPG",
    url_preview: "https://google.com",
    url_github: "https://github.com/Danielher/M3U2TrelloAppDanielHernandez",
  },
  {
    id: 5,
    titulo: "Landing_Page",
    descripcion: "Creacion de Landing Page con React JS y Tailwind",
    url: "../src/assets/LandingPage.JPG",
    url_preview: "https://instagram.com",
    url_github: "https://github.com/Danielher/My_Landing_Page",
  },
  {
    id: 6,
    titulo: "Juego del Ahorcado",
    descripcion: "Juego tradicional del ahorcado, con 9 intentos, realizadon con React JS y TS",
    url: "../src/assets/JuegoAhorcado.JPG",
    url_preview: "https://facebook.com",
    url_github: "https://github.com/Danielher",
  },
];
